### ISSUE TITLE
Submitted orders- view orders record

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#100]
View order record options is displayed only for Inspection orders but not for submitted orders.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/16IxYYA-9gqEcWB42UbMcV6aRTlQ1NndP/view?usp=drive_link

**Comment by himashree2024** [comment]
There is no option to view the order records


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/f945c044-2b72-4a62-8eac-392d4e32aafc
