### ISSUE TITLE
Submitted orders- import signature

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#101]
There is no option to import the signature for submit orders in the web app, but under roles user has access to do so. if so How?

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/16IxYYA-9gqEcWB42UbMcV6aRTlQ1NndP/view?usp=drive_link

**Comment by lamphi325** [comment]
Remove permission

**Comment by himashree2024** [comment]
closing the bug.
