### ISSUE TITLE
Inspector- Blank Order- New PIC with name "Administrator" is getting displayed in PIC column for blank orders

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#102]
Description: There is a new PIC called Administrator and that option is unavailable in the dropdown.
video: https://drive.google.com/file/d/1Jc3VIRVwbQbYSt0eeRlf0y6gYUVy8zNv/view?usp=drive_link
Credentials
url: https://devobadare.irisnextgen.com/
user name: [obadare.inspector@gmail.com](mailto:obadare.inspector@gmail.com)
password:123456

**Comment by himashree2024** [comment]
Tested and is not working fine. Attaching the screenshots.

on 27th - ![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/59f85ff2-9db5-465f-a7e9-164bc7c8e09d)
on 28th - 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/73dd5bd1-5905-49ca-b371-c916f46e02d5)

**Comment by lamphi325** [comment]
Administrator is admin account, just for test

**Comment by himashree2024** [comment]
So the admininstrator option will not be included in the filter dropdown?

**Comment by himashree2024** [comment]
Tested and is working fine in dev


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/2d1f5bcd-31e0-4bba-b368-cf48f074946f)
