### ISSUE TITLE
Submitted orders- download reports

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#103]
There is no option to Download the reports for submit orders in the web app, but under roles user has access to do so. if so How?

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/16IxYYA-9gqEcWB42UbMcV6aRTlQ1NndP/view?usp=drive_link

**Comment by lamphi325** [comment]
Remove permission

**Comment by himashree2024** [comment]
Tested and is working fine now. the download button is removed.
![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/b186bc59-95a1-4504-a7c2-c81e8ae4a8f6)
