### ISSUE TITLE
Submitted orders- download order details

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#104]
There is no option to download order details for submit orders in the web app, but under roles user has access to do so. if so How?

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/16IxYYA-9gqEcWB42UbMcV6aRTlQ1NndP/view?usp=drive_link

**Comment by lamphi325** [comment]
Remove permission

**Comment by himashree2024** [comment]
Tested and is working fine. The download button is removed.


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/33e24867-5042-4364-8d43-10ef571b2dfc)
