### ISSUE TITLE
Inspector- Notification- Users can view only half of the message under notifications box. 

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#105]
Description: User can only view half message of the notification
video: https://drive.google.com/file/d/16IZJjAVonXQgWn_smbj9ATEdYjeb9-KJ/view?usp=drive_link
Credentials
url: https://devobadare.irisnextgen.com/
user name: [obadare.inspector@gmail.com](mailto:obadare.inspector@gmail.com)
password:123456

**Comment by lamphi325** [comment]
task notify => navigation to home page
inspection order notify  => inspection page
submitted notify => submitted page
approved notify => approved page

**Comment by lamphi325** [comment]
scrolling the page to the bottom adds more the notification

**Comment by himashree2024** [comment]
Tested and is working fine.


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/b160723a-984b-45f9-9598-a802e558fded)
