### ISSUE TITLE
Submitted orders - delete submitted order

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#106]
"An error occurred while updating the enteries, see the inner exception for details" error message is getting displayed when user tries to delete a Submitted order.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1IQIHAM5qMNK_MXyewDcjfagbp_h7oDff/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine, user is able to delete the orders.

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/828eae7a-a04e-4d7b-bfcc-6b582d9047b6
