### ISSUE TITLE
Approved Orders- Export PDF

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#107]
"""There is no expoert option for the pdf but user can download tehe PDF.
1) When clicked on download pdf, its not getting downloaded for an order, but for some orders user can download.
2) the downloaded pdf doesn't have the image in it."""

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1pVYzKCSqMuRMXcEbKIsMvoSYWd5RmiGW/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/8eb478e0-aa3e-448d-9677-ec77e7831aac
