### ISSUE TITLE
Template- Download template

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#108]
"The requirements and dimensions mentioned in the template are not getting displayed instead  blank text boxes are getting displayed.
Also for NDT type there was template name that got displayed in the web but under downloaded pdf its blank."

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1APe4QuvhWB0SthC4lORZiinVL2I_5qYD/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/73ab14f6-2093-40c2-ad4f-d022f2adb294
