### ISSUE TITLE
System- User profile - Add new user

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#110]
"User when enters valid email id and then recieves the username and password for login, when user tries to login with the credentials given it sayd invalid.
Feedback: User was able to add new user but when tried to enter the phone with less than 9 digits it says invalid
so is the string is alowed to take more or equal to 9 digits"

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1r_UR7mAQWFvz_Gc1NFee0rOEzF1TXHJN/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and observed that, user when creates a profile with valid mail id, the email is not getting triggered.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/47c966f5-7cab-494d-b858-db08f350eeed

**Comment by himashree2024** [comment]
Tested and observed that when user enters valid mail id and creates a new profile the email with application login credentials are not getting triggered.

https://drive.google.com/file/d/1So9O2bVpJPGm-9BG8K-_femfGceIGJ78/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT.


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/b32aa511-a0f8-4a21-acdb-ddb2e7bb5684)



![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/3d9466e9-de94-42be-902c-5f783a015d6d)
