### ISSUE TITLE
System-user role- add new user role

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#111]
When added a new user role and assigned it to the valid user profile its not getting displayed under the list as the role is blank and when user login's to that profile its not reflecting the accesses given to that role and to that user.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1ufxmJFbfX5WDxRlwwsi1yVq292K1R3my/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and observed that the newly created user role when assigned to a profile is not getting displayed in the profile list.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/c37d9451-2b40-413b-acda-0ae9355c6376

**Comment by himashree2024** [comment]
Tested and is working fine in UAT


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/367bf7b1-038e-4aca-96aa-016dd907293e)
