### ISSUE TITLE
Your Profile- Change password

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#114]
User when enters the same password for current, new repeat password feilds and clicks on save, the system is accepting it. instead it should give an error message as current and new passwords are same.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1mpn3x8dTDwe0TBdcnNJfdLEC2gEvorW4/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/d4acb67c-f456-4836-b1d1-c520c12c5e84

**Comment by himashree2024** [comment]
1) When user tries to change the password and enter less than 6 char "This field is not in the correct format" message is getting displayed which is not appropriate.
2) When users enter different passwords in new and Repeate new password fields "new password does not match" is getting displayed which is not appropriate. "New passowrd and repreate new password does not match" like message which be better.
video: https://drive.google.com/file/d/1FzIPBCKP5--KY826woNbrT3uwEWHEpMJ/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT
https://drive.google.com/file/d/169-JP-tZ91c5IYLDiAbsuYDu79iFXIqk/view?usp=drive_link
