### ISSUE TITLE
Inspector- Dashboard- View task info

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#116]
User is able to drag and drop the task, as the inspector has only view access then drag and drop should be disabled.

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1Qzg3dqwrSn-HOONBiyRh7xtNHBVPOTBY/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine now.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/074b0bf0-003a-4ef1-88b0-c594892afd4c
