### ISSUE TITLE
Inspector- Inspection orders- View order info

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#117]
"User when viewing the attachments for the order, the link given is getting displayed on the whole screen instead of inside the items box."

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1nekmHxHt5NIBuP8bidvYHUjZR71XLKe4/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT
Admin 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/ff47109d-ecb0-4212-abd6-d5c84727f09a)


Inspector


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/847bcb5c-8eae-4467-a8bc-5db49507e144
