### ISSUE TITLE
Inspector- inspection orders- Export pdf

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#119]
when user clicks on export button, its downloading some unconformed file.

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1nekmHxHt5NIBuP8bidvYHUjZR71XLKe4/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/f85c0d02-8ff4-4193-9b93-8bb67c055120
