### ISSUE TITLE
Inspector- submitted order-view order information

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#120]
Tested and is not working as missing image icon is getting displayed instead of  the signature of the inspector and image that was uploaded by the inspector.

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1eYfMZQHkiKBuuyxB5aAStDEHeVPna9kX/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5c153c8c-5268-4d46-b683-a18447fd03da
