### ISSUE TITLE
Inspector - Approved orders- view order details

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#122]
Tested and is not working as missing image icon is getting displayed instead of  the signature of the inspector and image that was uploaded by the inspector.

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1vzJssUJJb36nrku-z8UgDMLUVrcLMidQ/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and is working fine. 
Video Reference: https://drive.google.com/file/d/1eKicUvYKln1DrQETtJHk3y00l1Dfdi_o/view?usp=drive_link
