### ISSUE TITLE
Inspector- Approved orders- download pdf

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#123]
"Tested and is working fine. 
but observed that when user clicks the download for multiple times only then the pdf is getting downloaded.
Also when opened the pdf directly there is no image but when opened the same pdf through folder its loading the image."

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1vzJssUJJb36nrku-z8UgDMLUVrcLMidQ/view?usp=drive_link

**Comment by himashree2024** [comment]
Observed that when user opens the downloaded pdf directly there won't be any image.
but when opened the downloaded pdf through system-download- select the downloaded pdf. only then the image is vissible.

**Comment by himashree2024** [comment]
Tested and observed the following
1) When user downloads the report observed the following
a) There was no date and timestamp for the images in pdf and excel.
b) There was no sign label for signature.
c) The allignment data under result in magentic partical inspection sheet is not proper in the excel.
d) under magentic partical inspection sheet its displaying "Obadare Tester :AINDT# 5605" inspector name along with a code in excel and PDF.
e) There are two extra blank sheets in the downloaded pdf.
f) For dimensions and item the label "BOX" is getting displayed in RED color under SUBS1 sheet in excel.
g) even observation is added under result without label.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/f70d0348-c54a-4150-a84b-8503553df685
[OrderNo_250320241_6c9c4e12-b126-4c79-b963-739ab9e3d413.pdf](https://github.com/Iris-Next-Gen/QA-Test/files/14737832/OrderNo_250320241_6c9c4e12-b126-4c79-b963-739ab9e3d413.pdf)
[OrderNo_250320241_54636c64-97a0-4dc7-9fe2-fe879e688478.xlsx](https://github.com/Iris-Next-Gen/QA-Test/files/14737833/OrderNo_250320241_54636c64-97a0-4dc7-9fe2-fe879e688478.xlsx)

**Comment by himashree2024** [comment]
Tested and observed that 
1) In 2nd page/sheet the data and the label are displayed together without any space.
2) The data under result in the table is not properly aligned in excel and in PDF part of the result is not displayed

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5d1d0722-5544-43c4-a636-aa9c932a6741)



![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5ed3165b-c109-4d32-961b-92183e2cc18b)





[OrderNo_260320242_32fe263e-9293-4617-9e38-2dda60ae8daf.xlsx](https://github.com/Iris-Next-Gen/QA-Test/files/14765932/OrderNo_260320242_32fe263e-9293-4617-9e38-2dda60ae8daf.xlsx)
[OrderNo_260320242_1729d14a-bda9-4239-ad58-4ebf0e248b8a.pdf](https://github.com/Iris-Next-Gen/QA-Test/files/14765933/OrderNo_260320242_1729d14a-bda9-4239-ad58-4ebf0e248b8a.pdf)

**Comment by himashree2024** [comment]
DEV COMMENTS


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/96b72dd3-c81e-4e72-b2bc-04f251622acb)


Tested and is working fine in UAT


[OrderNo_260320242_8028e462-1603-45fb-8986-2d686c095fea.pdf](https://github.com/Iris-Next-Gen/QA-Test/files/14901319/OrderNo_260320242_8028e462-1603-45fb-8986-2d686c095fea.pdf)
[OrderNo_260320242_90aa7a2d-c108-46c5-ba3b-3dadf29ee633.xlsx](https://github.com/Iris-Next-Gen/QA-Test/files/14901318/OrderNo_260320242_90aa7a2d-c108-46c5-ba3b-3dadf29ee633.xlsx)
