### ISSUE TITLE
Inspector- Your Profile- Change passward.

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#126]
User when enters the same password for current, new repeat password feilds and clicks on save, the system is accepting it. instead it should give an error message as current and new passwords are same.

**Credential**
url: [https://obadare.irisnextgen.com/](https://devobadare.irisnextgen.com/)
user name: obadare.inspector@gmail.com
password: testing1234

Video: https://drive.google.com/file/d/1Qzg3dqwrSn-HOONBiyRh7xtNHBVPOTBY/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and is working fine.
