### ISSUE TITLE
Login functionality- Valid credentials

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#129]
"Tested and is working fine for loggin in. 
But the FaceID is still on which is supposed to be removed. "

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1LZ6GlIxKBCFrm9RyFC5MlOZPVysEtHtk/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9)
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
