### ISSUE TITLE
Your Profile- edit user profile

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#133]
It is taking too long to save the changes. After change the profile picture and signature is taking time to load need to logout and then again sign in to see the changes saved in the user profile. 

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1mL6LSoejIFt1lEIrOccfXEEsaG3i73OE/view?usp=drive_link

**Comment by himashree2024** [comment]
⦁For profile when users changes the profile picture, the application loads for a long time. Also the profile picture and signature are enabled without clicking on edit (when added the image, sign how will it get saved?, is it auto save?). if its an auto save, then the changes are not getting saved.
⦁When user clicks on edit button and changes the profile and clicks on save the changes are not getting saved in the profile page, but the header is displaying the changed image.
version 3(9)
video:  
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT version 3(12).
Video:
https://drive.google.com/file/d/1CT1ZQtXc4TGVj-qLuWAI88JwnFlYKKrt/view?usp=drive_link
