### ISSUE TITLE
Your Profile-change password

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#134]
There is no any button for change password screen. 

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1mL6LSoejIFt1lEIrOccfXEEsaG3i73OE/view?usp=drive_link

**Comment by himashree2024** [comment]
⦁	The change password it not working, user when changes the pwd, it displayed a message as successful and also "password cannot be less than 6 characters".Also user is able to login with the old pwd only even thought it said changed successfully.
⦁	Also the application is loading for a long time when clicked on change password, but when got the message changed it successfully it will still be in the same change password page, its not logging out of the application.

video: https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link

**Comment by himashree2024** [comment]
⦁	The change password it not working, user when changes the pwd, it displayed a message as successful and also "password cannot be less than 6 characters".Also user is able to login with the old pwd only even thought it said changed successfully.
⦁	Also the application is loading for a long time when clicked on change password, but when got the message changed it successfully it will still be in the same change password page, its not logging out of the application.
in version 3(9).
video: https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and found that:
 When the inspector tries to change the password. if given less than 6 characters the change password is in disable mode, but the inspector doesn't understand why?. Need to display a message like  "the password must be at least 6 characters".

Video:
https://drive.google.com/file/d/1aLQo5HiNzXywdwx2-KnSpx8Z7b1hsbm0/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in uat version 3(13).
https://drive.google.com/file/d/13ZdRup8n9Cc2FG_vOXuAzWzcZSMbV0ib/view?usp=drive_link
