### ISSUE TITLE
Your Task- View task list

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#137]
Not being synchronised with the web app where the data are found different. Also, the "Go to order list" Screen has button for adding the blank order which needs to be removed. 

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/187gUWyG8CBZx9CbndRFYqSpxafKedloW/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9)
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
