### ISSUE TITLE
Inspection order- Filter calendar

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#139]
"There are issues such as:
- ""SELECTRANGE"" with no space in between.
- There is edit button while selecting the date which should be removed or else shoudl allow user to enter the date manually.
- The app is crashed while selecting the date manually. "

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/187gUWyG8CBZx9CbndRFYqSpxafKedloW/view?usp=drive_link
https://drive.google.com/file/d/1fxFOLkML1n1qkphKAPTCFf3oPcpp0LP5/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9).
https://drive.google.com/file/d/1ph9DGo7S3EA4vNs2nsRnTLxoMp9gzY_u/view?usp=drive_link
