### ISSUE TITLE
Inspection order- Add new items

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#140]
"Other text box is good to go. 
But Attachment text box: when user adds any attachments through web application, its not getting displayed for that item in mobile application."

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/187gUWyG8CBZx9CbndRFYqSpxafKedloW/view?usp=drive_link
https://drive.google.com/file/d/1KMNuyjpkrj1ejH8DgD_mR3ju07h58Egj/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9)
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
