### ISSUE TITLE
Inspection order- generate reports from the template

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#142]
"Other input box allows user to enter the value, but the gallery option while adding the image is not working. When Add image is pressed it navigates to teh gallery of the phone and the noting is also working there, but when gallery is pressed it navigates to the camera system function allows to capture the instant image but while saving it is not saved. 
Also, Template pattern is different than the user requirements. "

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/187gUWyG8CBZx9CbndRFYqSpxafKedloW/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9)
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
