### ISSUE TITLE
Inspection order- edit reports

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#143]
"While editing the items: 
- Dimension box are vanished.
- Every time when the going back to the item editing page it requires to insert the signature each time. "

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1pdbng_2hoYZXlmHxTcnZE2R_79xAi7sd/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9).
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
