### ISSUE TITLE
Inspection order- image editing in the reports

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#144]
"Image option is half working:
- when add image button clicked it navigates to the gallery function of the phone and allows to add the noting to the image as well.
- When gallery button is clicked it navigates to teh camera system function of teh phone allows to click the instant picture but is not saved when click on use photo option. "

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1pdbng_2hoYZXlmHxTcnZE2R_79xAi7sd/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in version 3(9).
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
