### ISSUE TITLE
Submitted order- view submitted orders list

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#146]
All the orders are not been synchronised. Web app has different number of List of submitted orders but the mob app while searching has different count of number. 

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1Gjy-5YDhldoCCu6v1LutLdyv9AcF86yt/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and is working fine in version 3(9).


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/409eaa27-34d4-481e-8975-d8200e5d9dfc)


https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
