### ISSUE TITLE
Submitted order- view unapproved orders list

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#147]
All the orders are not been synchronised. Web app has different number of List of unapproved orders but the mob app while searching has different count of number. 

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1Gjy-5YDhldoCCu6v1LutLdyv9AcF86yt/view?usp=drive_link

**Comment by himashree2024** [comment]
There is no order with status as unapproved can see the status with "Awaiting conformation only."
All the unapproved orders are nothing but the orders that are under submitted and not approved.
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and is synchronizing now in version 3(12).
Video: https://drive.google.com/file/d/1z78asrhlPjJ9PXLP0ZEwl-RID6CO0vU5/view?usp=drive_link
