### ISSUE TITLE
Submitted order- Edit unapproved submitted orders

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#149]
"While editing:
- The template name is vanished while showing the details.
- Signature has no insert button when editing the items details. 
- Result is pre-filled which should allow to choose from dropdown option. 
- While clicked on submit , it is taking time to submit the report. "

**Credential**
UAT version-3(7)
Username: obadare.inspector@gmail.com
Password: testing1234

Video: https://drive.google.com/file/d/1Gjy-5YDhldoCCu6v1LutLdyv9AcF86yt/view?usp=drive_link

**Comment by himashree2024** [comment]
Cannot test this as there are no unapproved orders under submitted order tab.
https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested in Dev version 1(23) 
When users approve and order then unapprove it and when try to submit the Unapproved orders by changing the data for items, observed that its blank under dimension and also for the template the field labels are missing.
 https://drive.google.com/file/d/1BIBHYx1ZgpRpQVJA_2dqiLXxNAW1YCy7/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and observed that after submitting the unapproved order the data under dimension is getting displayed blank in version 3(13).
video: https://drive.google.com/file/d/1dmuTBDT38gxoLORGJ56YWPezED1AQOxm/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in dev version 1(24).
https://drive.google.com/file/d/1sNUPRi-bBw7ef2890Bfm6AdHC4m2R7mH/view?usp=drive_link
