### ISSUE TITLE
Admin- Approved Order-Connection type/Dimensions details are missing in the downloaded report.

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#155]
Description: 
a) The details/data given for Dimensions under reports in mobile app are missing in the downloaded report in web app.
b) Also the header in the 1st page is missing.
c) "Preliminary test results" data is not in a proper alignment when user view the approved order.
d) observed that the date and time for the image is missing in the downloaded report
Steps to reproduce:
1) Submit an order with details entered under dimensions type in mobile app (admin dev account) for an order and submit the order.
2) Login to dev admin account on web application and approve the order.
3) Click on download button for the approved order.
the dimensions type/ connection data is missing in the downloaded pdf under approved orders.

pdf: https://drive.google.com/file/d/1dPMECThFudFmSNuE-LFu3_m6wU9y-fiT/view?usp=drive_link
video: https://drive.google.com/file/d/1ijndTt5fYZnzkv006-Dd6MmSTnaC_1Or/view?usp=drive_link
https://drive.google.com/file/d/1VVFPoh9XfxqX2mR_wSVnPEWXR2UkU0Fv/view?usp=drive_link

**Credentials**
https://devobadare.irisnextgen.com
Admin account:
username: nguyenletu2010@gmail.com
pwd: Nguyenletu2001

**Comment by himashree2024** [comment]
Also the few images are missing in the downloaded report.

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/9eb2dfda-ec58-4972-a1b1-53a7b367f4ea

**Comment by lamphi325** [comment]
fix description:
a - Fixed
b - When the customers send us export template, page 1st does not have a header
c - fixed
d - the template does not have date and time bellow images

**Comment by himashree2024** [comment]
Tested and is working fine in DEV
folder link: https://drive.google.com/drive/folders/1qpzC-MNVegqJ7jkLMvogzWmFiQyAN0ut?usp=drive_link
