### ISSUE TITLE
Inspector- Save Draft is not working for Inspection order and Your Task

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#187]
Description: Unable to add Picture through Add Image or or Gallery option for Your Task and Inspection orders.
Steps to reproduce: 
1) Login to the inspector account with valid credentials.
2) Go to Your task and select a date range and then select a task.
3) Click on the arrow button for the task, it navigates the user to the order page of that task,
4) Create a report for the task, and then click on Arrow button for the report of the item.
5) Click on add button for image. and then add the image and click on save button.
6) Go back and click on Save as Draft button.

Actual Result: User when clicks on Save as Draft button the task/ order is not getting saved and is not navigating back to the report page.

Video:  https://drive.google.com/file/d/1tSJ81advVNzJMd2uYkj0tpe5Q-d5_7Ho/view?usp=drive_link

Version 1(8)
username: obadare.inspector@gmail.com
pwd: 123456

**Comment by nvphi91** [comment]
pls retest

**Comment by himashree2024** [comment]
Tested and is working fine in version 1(13)
https://drive.google.com/file/d/1s2PLtAnp3ph3WlY0oK4f7HCqmwX64tNn/view?usp=drive_link
