### ISSUE TITLE
Noting on the image while uploading them while generating Report 

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#194]
**New Request By Obadare**:  The Text  (Noting) on the image is difficult to read.

**Comment by lamphi325** [comment]
Assign to Phi Nguyen

**Comment by himashree2024** [comment]
Tested and is working fine in Dev, once UAT is ready need to check there.
dev: https://drive.google.com/file/d/1qB8laH9204Y5Z0q-YQd8x4ZZlzIkxnbc/view?usp=drive_link

In UAT 3(7): 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/6b8cf9cb-8c72-475c-91fc-43d4d34c435b)

**Comment by nvphi91** [comment]
i don't build UAT

**Comment by himashree2024** [comment]
Tested and is working fine in DEV/UAT 
dev version 1(16), UAT version 3(9)
DEV: https://drive.google.com/file/d/1qCyGgZ_yYodMceeJpy2djBXVQUDvu8jA/view?usp=drive_link
UAT: https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link
