### ISSUE TITLE
Inspector- "Nullable object must have a value" message is getting displaying when clicked on few tasks and submitted orders.

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#205]
Description: "Nullable object must have a value" message is getting displayed when inspector tries to open a task or submitted order. along with the message it is also displaying wrong order number.
Steps to reproduce:
1) login to the application with valid credentials.
2) go to your task tab and click on the task.
3) go to submitted orders tab and click on an order.

Observed that this error is getting displayed only for few tasks and submitted orders.
Credentials:
Version 1(11)
Username: obadare.inspector@gmail.com
Pwd: 123456
video: https://drive.google.com/file/d/1FZZB1oj1Ef11FhkA6agLW-YuMe4xsukt/view?usp=drive_link

**Comment by nvphi91** [comment]
Retest in version 1(12)

**Comment by himashree2024** [comment]
Tested and is working fine now
https://drive.google.com/file/d/1s2PLtAnp3ph3WlY0oK4f7HCqmwX64tNn/view?usp=drive_link
