### ISSUE TITLE
Admin- Approved orders- the data under "Preliminary test results" is missing.

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#208]
description: The data under "Preliminary test results" is missing for approved orders, user was able to see the data under submitted orders.
Precondition: Submit an order from mobile with data for dimensions /connection type
Steps to reproduce:
1) Login to the application.
2) go to submitted orders, and click on view button and check for the data for dimensions and then approve it.
3) Go to approved order and click on view button for that order.
Result: observed that the data under "Preliminary test results" was missing for one of the items.

**Credentials**
https://devobadare.irisnextgen.com
Admin account:
username: nguyenletu2010@gmail.com
pwd: Nguyenletu2001

video link from mobile: https://drive.google.com/file/d/1FZZB1oj1Ef11FhkA6agLW-YuMe4xsukt/view?usp=drive_link
https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/88d9ba6f-666c-4a4b-99a8-695a5f7a69db

**Comment by lamphi325** [comment]
Assign to Phi Nguyen.
He is in charge of mobile

**Comment by himashree2024** [comment]
Tested and is working fine now.
 https://drive.google.com/file/d/1g3slwZJp4O4JHv_paZIGghklJ5KJ2lws/view?usp=drive_link
