### ISSUE TITLE
Inspector- The data under dimensions is missing and images load after few seconds under submitted order when the status is "Awaiting conformation"

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#222]
Description: The data under dimensions/connection is is blank under submitted orders when the status is "Awaiting Conformation"

Steps to reproduce:
1) login to the application with valid cred.
2) Submit an inspection order with all the details.
3) Go to submitted order for that order.
4) click on view button for that order.
5) view the dimension/connection type in the report for that order.

Result: the dialogue box for that field was blank.

video: https://drive.google.com/file/d/1KuuEBr8LvoDedVNXCMFdKCQbuKGUCm8h/view?usp=drive_link
https://drive.google.com/file/d/1s2PLtAnp3ph3WlY0oK4f7HCqmwX64tNn/view?usp=drive_link

**Comment by nvphi91** [comment]
This report has no dimensions

**Comment by himashree2024** [comment]
tested and is working fine now. the data added is geting displayed correctly under submitted orders.
https://drive.google.com/file/d/1Sx_7vp6GkADBVDOLN28fDCUQzMBXNdUI/view?usp=drive_link
https://drive.google.com/file/d/1GbCBJF4R5py4aGnxVbI4wxwSpI7nmcsR/view?usp=drive_link
https://drive.google.com/file/d/1rLSAzoYkMkws0XuQBilEaiomozD0AcaK/view?usp=drive_link
