### ISSUE TITLE
Admin- The data under " Preliminary test results" for an item is getting displayed wrong when compared with the actual data given for that item

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#223]
Description: The data under " Preliminary test results" for an item is getting displayed wrong when compared with the actual data given for that item

Steps to reproduce:
1) Login to the application with valid credentials.
2) Go to your task and open a task and add an item.
3) create report for that item by adding images and connection type data and save as draft.
4) go to inspection order tab and open the same order and add images and test results for another item.
5) click on submit button.

result: After submitting the order when checked in the web application it displayed data of another item under " Preliminary test results"   for an item.

Credentials:
**Credentials**
https://devobadare.irisnextgen.com
Admin account:
username: nguyenletu2010@gmail.com
pwd: Nguyenletu2001

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/03cc1f63-5f53-46ee-8dea-634ad5292fbf

https://drive.google.com/file/d/1s2PLtAnp3ph3WlY0oK4f7HCqmwX64tNn/view?usp=drive_link

**Comment by nvphi91** [comment]
@lamphi325 verify the data again

**Comment by himashree2024** [comment]
Created a new order and flowed it till submission. Compared the data given and displayed. It working fine
video: 

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/e7923809-1313-4a2f-8ab3-e34aa698e470

mobile: https://drive.google.com/file/d/1Yhv7YC8Rtl_BiPb1a2OeHN_-YvvOf45H/view?usp=drive_link
