### ISSUE TITLE
Inspector- Submission of an order is tasking longer time than usual.

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#226]
Description: Submission of an order is tasking longer time than usual.
Steps to reproduce:
1) Login to the application.
2) Go to your task or inspection order tab.
3) click on view button for an order or task.
4) create report and click on submit button.

Result: submission of the order is taking long time
 
version 1(13)
username: obadare.inspector@gmail.com
pwd: 123456

video: https://drive.google.com/file/d/1MWGPTPSJgq1fBrm3ssTvr7jNN-MATdFd/view?usp=drive_link

**Comment by nvphi91** [comment]
It's not bug
