### ISSUE TITLE
Inspector- The status for the task is not getting changed to doing or done, when the user works on that task and submits that task. 

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#236]
Description: The status for the task is not getting changed to doing or done, when the user works on that task and submits that task. 
Steps to reproduce:
1) Login to the application with valid cred.
2) Go to your task tab and click on any task.
3) Add items and create reports for the items.
4) Click on any item under report page and add the images and other data as required.
5) Insert the signature and click on save.
6) Submit the order under your task.
7) Go back to Your task and check for the status
Result: The status is not getting changed for the task.

dev version 1(16), uat version 3(9)
username: obadare.inspector@gmil.com
pwd: 123456.

dev video: https://drive.google.com/file/d/1qCyGgZ_yYodMceeJpy2djBXVQUDvu8jA/view?usp=drive_link
uat video: **https://drive.google.com/file/d/18-x01jw8R02HtOfqumadzWXeJq8duOkL/view?usp=drive_link**

**Comment by nvphi91** [comment]
@lamphi325 check again

**Comment by himashree2024** [comment]
Tested in dev version 1(22) and UAT version 3(12) and is not working.
video: 

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/931a48d8-2c61-4f0d-8878-0a63bb396189



![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/e02529eb-4c1c-4fe3-80f6-a3f97116e524)
![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/445d6692-8250-4954-9bbc-3b7b72640dcb)

https://drive.google.com/file/d/1J1gXxwUEzSGSOBXFEbj2lxggf2SulBMt/view?usp=drive_link
https://drive.google.com/file/d/1q0R7HlKh9_cUIcTkfefyDaUj_v8qgv8k/view?usp=drive_link

**Comment by himashree2024** [comment]
The status has to be changed manually , in future versions the plan is to change the status automatically
