### ISSUE TITLE
Admin- Approve Order -download report

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#248]
When downloaded the Excel and Pdf file Observed 
a) The letter for results is splitting into two half's in the pdf.
b) There are 2 blank sheets in the pdf.
c) In the images page below the image user see the fields and data for Scope, results but when coming to observation there is no field label for it but the data given for the observation was just getting displayed in pdf and Excel.
d) The signature image is getting displayed but it doesn't display the Author of the signature (inspector). which is confusing for the users in pdf and excel.
 When filtered on Tech, The filter is getting auto applied as soon as user selects the tech from the dropdown before clicking on Apply button.
NDT type field is getting displayed under item, but user does not give any NDT type for item, even though its taken from the template then it should display that data under item for NDT type field instead of blank.

UAT folder link: https://drive.google.com/drive/folders/1GMY28gudc_pfoAen3vNlePV6nkNxteEq?usp=drive_link
DEV folder link: https://drive.google.com/drive/folders/1aXGCiILIPuU6BOpMVngF15gA_yDhKw51?usp=drive_link

**Comment by himashree2024** [comment]
observed the following when downloaded the reports through excel and PDF.
1) The alignment is not proper under result in the template sheet(2nd sheet) in excel.
2) The the label is lengthy the data for that field is getting attached to it in the pdf.
 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/0e4b1120-956e-4e31-acb0-c6b77180c241)


3) The result data in 2nd page is only getting displayed half.
 

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/1ec1ebeb-41ee-4898-9fad-c6d98c2625d3)



4) extra blank sheets are getting displayed in the pdf report.
5) when user select a tech from the dropdown in the filter the list is getting filtered automatically before clicking on apply button. 
Folder link:  https://drive.google.com/drive/folders/1S8Dcc7gpJEGyFmS59YSBmHUUEoe-IZmo?usp=drive_link

**Comment by lamphi325** [comment]
filter Tech do not fix. select dropdown auto filter by item select

**Comment by himashree2024** [comment]
Tested and observed that 
1) In 2nd page/sheet the data and the label are displayed together without any space.
2) The data under result in the table is not properly aligned in excel and in PDF part of the result is not displayed

![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5d1d0722-5544-43c4-a636-aa9c932a6741)



![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5ed3165b-c109-4d32-961b-92183e2cc18b)





[OrderNo_260320242_32fe263e-9293-4617-9e38-2dda60ae8daf.xlsx](https://github.com/Iris-Next-Gen/QA-Test/files/14765932/OrderNo_260320242_32fe263e-9293-4617-9e38-2dda60ae8daf.xlsx)
[OrderNo_260320242_1729d14a-bda9-4239-ad58-4ebf0e248b8a.pdf](https://github.com/Iris-Next-Gen/QA-Test/files/14765933/OrderNo_260320242_1729d14a-bda9-4239-ad58-4ebf0e248b8a.pdf)

**Comment by himashree2024** [comment]
DEV COMMENTS


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/96b72dd3-c81e-4e72-b2bc-04f251622acb)


Tested and is working fine in UAT/DEV

UAT doc

[OrderNo_260320242_8028e462-1603-45fb-8986-2d686c095fea.pdf](https://github.com/Iris-Next-Gen/QA-Test/files/14901319/OrderNo_260320242_8028e462-1603-45fb-8986-2d686c095fea.pdf)
[OrderNo_260320242_90aa7a2d-c108-46c5-ba3b-3dadf29ee633.xlsx](https://github.com/Iris-Next-Gen/QA-Test/files/14901318/OrderNo_260320242_90aa7a2d-c108-46c5-ba3b-3dadf29ee633.xlsx)

DEV doc


[OrderNo_22032024_8c81ef3c-090a-4b33-8e02-951098f63435.pdf](https://github.com/Iris-Next-Gen/QA-Test/files/14901328/OrderNo_22032024_8c81ef3c-090a-4b33-8e02-951098f63435.pdf)
[OrderNo_22032024_1cefc27b-97ef-49cd-a262-18df4de38c82.xlsx](https://github.com/Iris-Next-Gen/QA-Test/files/14901327/OrderNo_22032024_1cefc27b-97ef-49cd-a262-18df4de38c82.xlsx)
