### ISSUE TITLE
Admin- Duplication orders are getting displayed in the search dropdown for submitted Order.

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#252]
User when tried to search with job no 19, it displayed 3 orders with 2 same order no and one with different order no in the dropdown but under submitted order list we have only one order with that job no.

https://drive.google.com/file/d/19hL4JgEXNt5e1y7t55tPhoOPMmggyQap/view?usp=drive_link

**Comment by lamphi325** [comment]
Old data created 14/03

**Comment by himashree2024** [comment]
Tested and is working fine now
https://drive.google.com/file/d/1e49BYGtPa7haqHNbVBjGG52uqTSQQc9L/view?usp=drive_link
