### ISSUE TITLE
UAT- Profile-User giving same password while changing the password does not return the error message

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#31]
Description: User is still able to give same passwords in all the feilds during change password without any error message.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/1Zc-1X0viLjTTx0Q9K6nxZ3RTZMc1mXP5/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/d2a3d91a-96fc-4920-8349-610c802ee19a
