### ISSUE TITLE
UAT- System Management- Third Party- Create a new thrid party-  undefined undefined replaces the real third name while inactivating.

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#33]
User when inactivates the third party the name is getting displayed as undefied undefined.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video:(https://drive.google.com/file/d/12_VZqIEgjJHQdeb-CKweSMWEtckR4MgA/view?usp=drive_link)

**Comment by himashree2024** [comment]
Tested and is working fine, when changed the TP to inactive state, the name of the TP didn't change.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/8af132fb-e908-4bbb-957a-3413b70104a0
