### ISSUE TITLE
Admin- Inspection orders- User is able to give the online links but not able to give the links from the local

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#36]
Description: User is able to give online links but unable to give the links from the system for inspection orders add item.

**Credentials**
https://devobadare.irisnextgen.com
Admin account:
username: nguyenletu2010@gmail.com
pwd: Nguyenletu2001
video: https://drive.google.com/file/d/1ff2ZRMd3kKR2naL4T02ExWpCCGvzyfFN/view?usp=drive_link

**Comment by lamphi325** [comment]
Link is www, not path of local computer
