### ISSUE TITLE
Course- Resource adding inside the course

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#37]
There is no add new resource button for admin user.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/1M49fq1aMu9U9kwHrsc8HiLD5hU9w-HN0/view?usp=drive_link
https://drive.google.com/file/d/1uQ9-s4750KIIWn7cuLJpbvAwiNp3IamR/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/53b16a9c-58bb-4e2e-a358-8dfd965651dc
