### ISSUE TITLE
Inspector- User is able to access gallery option but not Camera for inspection orders.

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#43]
description: Gallery is accessed but the camera option is not working, it navigates to the camera application but does not save the image.
- When users click on Gallery it should go to the Gallery where we have list of images and user clicks on Add Image it should take user to the camera and allow to click a picture, but here its opposite click on add image its takes user to gallery and when clicks on gallery it allows user to take image.

**Credentials**
version: 1(4)
Username: obadare.inspector@gmail.com
pwd: testing1234

video: https://drive.google.com/file/d/1UeJwshkRSh4m0ojvL4Nwgb9OhUCjBwoq/view?usp=drive_link

**Comment by himashree2024** [comment]
User is now able to access both add photo and camera options but after adding the images and when users tried to view the item again, the Images are getting loaded very slowly 
Added the video for your reference.
video: https://drive.google.com/file/d/1FZZB1oj1Ef11FhkA6agLW-YuMe4xsukt/view?usp=drive_link

**Comment by nvphi91** [comment]
- improve in next phase

**Comment by himashree2024** [comment]
tested and is working fine.
https://drive.google.com/file/d/1s2PLtAnp3ph3WlY0oK4f7HCqmwX64tNn/view?usp=drive_link
