### ISSUE TITLE
Reports- Save reports

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#46]
There is no option to save the reports, user can save the report during creation but not after creation whenever required.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/1QO9FB2bw73mULfZTOGCVL_NGktwJB-k5/view?usp=drive_link

**Comment by himashree2024** [comment]
working fine
