### ISSUE TITLE
Calendar-Show list of events (monthly) 

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#47]
The events that are at the right corner of the calendar screen, the list of events is not visible it gets underlapped. 

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/1FC3bYG1HXyGTiLDj0V4fSw2cMWGjF_5d/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/7d3f3982-8710-4748-ab27-dc570c0646d5
