### ISSUE TITLE
Dashboard of Admin- Show Calendar

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#59]
No Calendar is shown in the dashboard.
**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/1H7ogHTHDkRnmMK1EfEqwekMdi_RzFmxF/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/1e09f012-8257-4a87-81a5-a4ffc2f9a02e
