### ISSUE TITLE
Dashboard- Access event in Calendar

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#60]
Cant access the event in calendar in dashboard. 

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/1H7ogHTHDkRnmMK1EfEqwekMdi_RzFmxF/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/29dcacea-513c-41dd-acf0-6b0a4e0e345b
