### ISSUE TITLE
Help Guide & Support- Show list of support action

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#67]
User is able to view the list of support but when clicked on them no action is been performed.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/12m2kEMGf5yAokmtY4paZe3SzoNOqcO2H/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/2e6ca06b-db8f-4e26-a914-60eac3236507



https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/20aaa5a7-587d-44cd-9b15-360b4f8e2f24
