### ISSUE TITLE
Messages-Show recent box chat

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#77]
blocked due to chat, as the message buton is not working.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/12m2kEMGf5yAokmtY4paZe3SzoNOqcO2H/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/65d7b993-09fa-4cd2-8770-827ceda12e6f)
