### ISSUE TITLE
Messages- Call users 

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#81]
The call button is not working as no action is been performed or a call screen gets opened.

**Credentials**
URL: [https://wombat.irisnextgen.com/](https://devwombat.irisnextgen.com/) 
Username: lamphi325@gmail.com 
Password: Abc@123

Video: https://drive.google.com/file/d/12m2kEMGf5yAokmtY4paZe3SzoNOqcO2H/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine
able to call

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/c5bba63d-b799-48ab-8a14-0e38f30734a7
