### ISSUE TITLE
Admin- Notification: "Data does not exists" message gets displayed for the orders notification and Users can only view half message in the notification box. 

### ISSUE THREAD

**Issue by himashree2024** [Iris-Next-Gen/QA-Test#85]
Description: User when views the notification for orders, it  displays an error popup with "Data Does not exist"
Also user is unable to view the full message notification.

**Credentials**
https://devobadare.irisnextgen.com
Admin account:
username: nguyenletu2010@gmail.com
pwd: Nguyenletu2001

video: https://drive.google.com/file/d/1kIqOCZD91CGPeR8-d8RDzPWD4rl_aTo4/view?usp=drive_link

**Comment by lamphi325** [comment]
Obadare Admin can delete order
When order deleted, let user click to notification just to show message: "Data does not exists"

**Comment by lamphi325** [comment]
The Order and Report can delete by Obadare Admin
If it has been deleted, a full message will be displayed

**Comment by himashree2024** [comment]
Tested and user is able to see the notification and for the message display its still only half for admin account


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5c8fdcf1-a77f-45eb-b3a2-0361500eabd4

**Comment by himashree2024** [comment]
Tested and is working fine.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/ab169d7f-6001-4d09-a36b-31847fda484a
