### ISSUE TITLE
Dashboard- Edit task

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#87]
User is not able to edit or delete the done task which is the user requirements but 
User is able to edit the status of the done task by drag and drop which internally is editing the done task so Drag and drop should be disabled for the done tasks.

**Credential**
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001 

Video: https://drive.google.com/file/d/19Ofpvky-A_JDZA7GHMFziun-la8cRBKU/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine for Submitted or done task. 
However, it should not be same for doing tasks, user is able to edit the status manually and change from doing to new but cannot drag and drop from doing to new.

Video https://drive.google.com/file/d/1c_T1111u97foO8gBifIMFWPwKQNhujyM/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine. User is unable to edit or drag and drop the done task
video:  https://drive.google.com/file/d/1WpdXVYvjbDHL8cMMSGxwt6dEGrrMDEdY/view?usp=drive_link
