### ISSUE TITLE
Inspection Order- View order 

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#90]
User when viewing the list details, the entered attachment link is not alliging with the screen, the details are out of the screen box.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1QbTI2LCmdUX5T_pHK4bjomTRHp_rXrgl/view?usp=drive_link

**Comment by himashree2024** [comment]
tested and is working fine 

https://drive.google.com/file/d/10wZSYW_cmx_2Nl5oxmSdZ3qHbRlwVL8F/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and observed the same issue again , users when view the records for the inspection order observed it and also the uploaded doc for the item is missing under view record.
 https://drive.google.com/file/d/1_L3a0ZEprsr2SwOfufXL92mppz6tmY2V/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is not working


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/b49438f4-643e-4b14-b7ec-5ebb5c451221)

**Comment by himashree2024** [comment]
Tested and is working fine in UAT.


![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/5b7a891c-0181-43de-87bd-a84996073b9e)




![Image](https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/1c2f8584-fdb7-4d52-be10-3cf2187d72df)
