### ISSUE TITLE
Inspection  Orders- Delete order

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#91]
Error message "An error occurred while updating the enteries. see the inner expcetion for details" popped up while trying to delete the order.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Tested data: Order no: 87678567
Video: 
https://drive.google.com/file/d/1QbTI2LCmdUX5T_pHK4bjomTRHp_rXrgl/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine.

https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/88268179-e3d4-4a90-8f53-f0d4fcb66059

**Comment by himashree2024** [comment]
Tested and observed the issue again in UAT
https://drive.google.com/file/d/1phI0s5cKIO8rL89o48dr1yQqz3C1KCCJ/view?usp=drive_link
https://drive.google.com/file/d/1oarZARaf6S4Jgl2d_yhXre4LZnKK72qf/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT


 https://drive.google.com/file/d/1_L3a0ZEprsr2SwOfufXL92mppz6tmY2V/view?usp=drive_link
