### ISSUE TITLE
Inspection  Orders- import attachment

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#94]
User is able to give online links but unable to give the links from the system.

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1ff2ZRMd3kKR2naL4T02ExWpCCGvzyfFN/view?usp=drive_link

**Comment by lamphi325** [comment]
Link is world wide web, not local path computer

**Comment by himashree2024** [comment]
tested and is working fine.

Video Reference: https://drive.google.com/file/d/1nVcHuFVtuJYAFTQ56kJQS4DmrEHOm1x8/view?usp=drive_link
