### ISSUE TITLE
Inspection  Orders- Filter by Date

### ISSUE THREAD

**Issue by manishakhatri07** [Iris-Next-Gen/QA-Test#95]
It is not working, user is able to see the rest of the order as well while searching for one date. 

**Credential** 
URL: https://obadare.irisnextgen.com/business/system-management/group-user-management 
Username: nguyenletu2010@gmail.com
Pwd: Nguyenletu2001

Video: https://drive.google.com/file/d/1NtSHtwGVYxt7SJQSYE8SelZGF8ltMGqk/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and found new feature as match any or match all. However, it is not doing its function, when selected the date the data of one day previous to selected  is shown. 

For example: if I select 8/3/2024 the data of 7/3/2024 is shown. 

Video Reference: https://drive.google.com/file/d/1Ab1UfMzaSmmmCZnkwdEu0ljuIdHnW8qC/view?usp=drive_link

**Comment by himashree2024** [comment]
Tested and is working fine in UAT, please find the video attached for your ref.


https://github.com/Iris-Next-Gen/QA-Test/assets/160978632/b32df55e-79f7-44f6-bc94-1e82d174a335
